### ISSUE TITLE
GPU resource requirement for Mochi inference

### ISSUE THREAD

**Issue by Aristo23333** [hao-ai-lab/FastVideo#100]
Hi author!
1. I am trying to use your FastMochi inference(with your sh code) on an H800 with 80 GB memory. But I get OOM wrong. What is your GPU resource for this model inference? 
2. I also tried to change the num_frames from your settings to 60 but didn't get a suitable video result. 
3. I find that the height (480) / width (848) seems necessary to maintain a fixed ratio, can I adjust that?
Could you give me some advice? Thank you!

**Comment by rlsu9** [comment]
Thanks for your feedback
1. for script inference_mochi_sp.sh, num_frames = 163 will lead to OOM on 80G gpu, we suggests you to try with 93 frame, it should works
2. I have tried with num_frames to 60 and it generate a video that I thought is reasonable. Could you please share the result you get so we will try to find out the cause.
3. The compress ratio for VAE is 8 for height and width for mochi, so any scale for 8 should works, i have tried 400x800 and it does works.
