### ISSUE TITLE
Any plans for image-to-video?

### ISSUE THREAD

**Issue by xiankgx** [hao-ai-lab/FastVideo#102]
Dear authors, great work, but any plans for image-to-video?

**Comment by rlsu9** [comment]
Thanks for your interested, Hunyuan is considering release their I2V model in Jan 2025, we will apply the fastvideo framework to accelerate it by that time.

**Comment by yjhong89** [comment]
- Hunyuan Video I2V is released.
- https://github.com/Tencent/HunyuanVideo-I2V
