### ISSUE TITLE
[Feature] cpu only work

### ISSUE THREAD

**Issue by malv-c** [hao-ai-lab/FastVideo#116]
### Motivation

no gpu here

**Comment by zhisbug** [comment]
Hi, Do you mean if fastvideo supports cpu-only inference?

**Comment by malv-c** [comment]
as it is wrote gpus i assume no
if yes forgive me
if no can you  make it please

**Comment by rlsu9** [comment]
Thanks for you feedback, we currently have no plan for supporting cpu only inference.
