### ISSUE TITLE
Why there is no OOM when performing distilling?

### ISSUE THREAD

**Issue by GFENGG** [hao-ai-lab/FastVideo#117]
### Environment

I found the mini GPU memory required by hunyuanVideo is 60GB from its official github, and is there no OOM if the  student_dit and teacher_dit are used in one pipeline when using fastvideo distilling?

and the sequence parallel seems not used in "scripts/distill/distill_hunyuan.sh" with [--sp_size=1]

### Describe the bug

None

### Reproduction

None

**Comment by foreverpiano** [comment]
The student model and teacher model are two different models in the distillation process. Distillation needs more space to store the optimizer state and gradients, so the memory usage during distillation is larger than during inference.

Yes, sp_size=1 represents the data parallel model.

**Comment by GFENGG** [comment]
> The student model and teacher model are two different models in the distillation process. Distillation needs more space to store the optimizer state and gradients, so the memory usage during distillation is larger than during inference.
> 
> Yes, sp_size=1 represents the data parallel model.

Thanks for your reply!  
Considering the optimizer and gradient, the required memory for training is approximately 2-3 times that of inference. If inference requires at least 60G (from hunyuan official git), then the distillation process will require at least 120G~180G? Why is there no OOM problem when only the DDP is used in the distilling process?

**Comment by foreverpiano** [comment]
Can you share with your running command and env?

**Comment by GFENGG** [comment]
> Can you share with your running command and env?

Sorry, I was just expressing my confusion, not the actual problem encountered with the code. I haven't run the program yet, and I will try later.

**Comment by jzhang38** [comment]
We use fsdp, not DDP
