### ISSUE TITLE
Will there be a stable release of fastvideo soon?

### ISSUE THREAD

**Issue by WangRongsheng** [hao-ai-lab/FastVideo#87]
Thank you for your awesome work. Will there be a stable release of fastvideo soon? I would like to try it on hunyuanvideo.

Recently, diffusers merged a [PR](https://github.com/huggingface/diffusers/pull/10136) related to hunyuanvideo. Is this compatible with fastvideo?

**Comment by foreverpiano** [comment]
@WangRongsheng
Thank you for your interest in fastvideo. 
1. We will release the checkpoint soon.
2. Yes, it's compatible, but we recommend using our codebase since we have implemented sequence parallel for fast inference and we also provide a Gradio demo.

**Comment by WangRongsheng** [comment]
@foreverpiano thank you.
