### ISSUE TITLE
Any plan to distill HunyuanVideo with CausVid?

### ISSUE THREAD

**Issue by ltzheng** [hao-ai-lab/FastVideo#92]
Thanks for the great work! I see adding DMD is in your roadmap. The new method CausVid (Project page: https://causvid.github.io) looks super promising. Do you have any timeline to adopt it here? Btw what is the compute (GPU hours) in the current HunyuanVideo distillation?

**Comment by jzhang38** [comment]
> Btw what is the compute (GPU hours) in the current HunyuanVideo distillation?

Roughly 32H100 for 12 hours.

> The new method CausVid (Project page: https://causvid.github.io/) looks super promising.

Yes, we are aware of this method. The authors did not release their code so this might take longer.
