### ISSUE TITLE
Re: HunyuanVid fp8 model, multigpu inference/sageattention, Distillation

### ISSUE THREAD

**Issue by gitanon112** [hao-ai-lab/FastVideo#94]
Hello,

First wanted to say great work and thanks a lot for open-sourcing the code, it's great! Had a few questions I wanted to ask.

1) HunyuanVideo just released their [fp8 model](https://huggingface.co/tencent/HunyuanVideo/tree/main/hunyuan-video-t2v-720p/transformers), any plans to integrate this + would this reduce memory costs?

2) Looking at inference_hunyuan.sh, it seems that multi-gpu inference is supported, is this correct? 

3) I see we are using flash-attn, would it be possible/easy to use sageattention/sageattention 2 instead for speedups on RTX4090? If it seems easy, I can try implementing it myself. 

4) I see alot of stuff regarding distillation + looked online/github repos you mentioned, but still confused regarding what it is exactly. Any useful resources on the topic I could use?

Thanks so much!!

**Comment by jzhang38** [comment]
1. Yes.
2. Yes.
3. We tried sage attention but found no speed up on A100/H100. Seems that it is specific to 4090. We will add sage attention together with fp8 to support 4090.
4. You can refer this paper: https://arxiv.org/abs/2303.01469

**Comment by gitanon112** [comment]
Sounds good, thanks so much for the prompt/detailed response!
