### ISSUE TITLE
Unable to save Lora Finetuned model

### ISSUE THREAD

**Issue by epinnock** [hao-ai-lab/FastVideo#96]
I'm able to finetune Mochi 1 using the provided script, but currently its failing whenever I attempt to save the model. I get the following error:
```python
AttributeError: type object 'MochiPipeline' has no attribute 'save_lora_weights'
```
I'm able to generate with the base model and the training works just fine. Its just unable to find the function 'save_lora_weights'

**Comment by jzhang38** [comment]
Can you try it again? #97

**Comment by epinnock** [comment]
Thanks it worked I was able to save the lora layers.

**Comment by epinnock** [comment]
@jzhang38 for inference would  i merge it into the FastVideo/FastMochi-diffusers or the genmo/mochi-1-preview which was used in the finetuning? Also would I need to run the distilling processing again?
