### ISSUE TITLE
Can I use multi GPUs to extract validation_text_embeddings?

### ISSUE THREAD

**Issue by splinter21** [hao-ai-lab/FastVideo#98]
https://github.com/hao-ai-lab/FastVideo/blob/main/scripts/preprocess/preprocess_hunyuan_data.sh#L28C1-L28C28

Now it uses only 1 GPU.

**Comment by jzhang38** [comment]
Yeah, I did not write multi-gpu logic for it because we normally only need to sample a ;imited number of validation videos. 

Any specific reasons that you want a multi-GPU version?
